backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/en/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Categories', name: 'categories', widget: 'list'  }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'about'
    label: 'About'
    folder: 'content/en/about'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Type', name: 'type', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
